name: Regression Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults: 
  run:
    working-directory: build

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: configure
      run: cmake ..
    - name: build
      run: make
    - name: run unit tests
      run: ./tests    

    # simulator runs
    - name: run test-tiny
      run: ./cgraphitti -c ../Testing/RegressionTesting/configfiles/test-tiny.xml
    - name: verify test-tiny
      run: diff ../Testing/RegressionTesting/TestOutput/test-tiny-out.xml ../Testing/RegressionTesting/GoodOutput/test-tiny-out.xml

    - name: run test-small
      run: ./cgraphitti -c ../Testing/RegressionTesting/configfiles/test-small.xml
    - name: verify test-small
      run: diff ../Testing/RegressionTesting/TestOutput/test-small-out.xml ../Testing/RegressionTesting/GoodOutput/test-small-out.xml

    - name: run test-small-connected
      run: ./cgraphitti -c ../Testing/RegressionTesting/configfiles/test-small-connected.xml
    - name: verify test-small-connected
      run: diff ../Testing/RegressionTesting/TestOutput/test-small-connected-out.xml ../Testing/RegressionTesting/GoodOutput/test-small-connected-out.xml

